config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 scope module: :public do
  root to: 'homes#top'
  get '/about', to: 'homes#about'

  resources :post_teas, only:[:index, :new, :create, :show, :edit, :update, :destroy]
 end

 namespace :admin do
  root to: 'homes#top'
  resources :genres, only: [:index, :create, :edit, :update]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_teas, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :post_teas, dependent: :destroy
  validates :name, presence: true
end

app/models/post_tea.rb
class PostTea < ApplicationRecord
  has_one_attached :image

  belongs_to :customer
  belongs_to :genre
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
   if @genre.save
    redirect_to admin_genres_path
   else
     @genres = Genre.all
    render "index"
   end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
   if  @genre.update(genre_params)
    redirect_to admin_genres_path
   else
    render "edit"
   end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
　   super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected
  #管理者のログアウト後の移管画面指定
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-3 offset-lg-1">
      <h4>ジャンル編集</h4>
    </div>
  </div>

  <% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <%= form_with model: @genre, url:admin_genre_path do |f| %>
  <div class="row-10">
    <div class="col-10 mt-5">
      <%= f.label :name, "ジャンル" %>
      <%= f.text_field :name %>
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-3 offset-lg-1">
      <h4>ジャンル一覧・追加</h4>
    </div>
  </div>

  <% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <div class="row-10">
    <div class="col-10 mt-5 mb-5">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <%= f.label :name, "ジャンル名" %>
      <%= f.text_field :name, placeholder: "ジャンル名" %>
      <%= f.submit "新規登録", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>

  <div class="row">
    <div class="col-4">
      <table class="table mt-2">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header>
    <% if customer_signed_in? %>
      <li>
        <%= link_to '投稿フォーム', new_post_tea_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_customer_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path %>
      </li>
    <% end %>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tea</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>